### ISSUE TITLE
Order html

### ISSUE THREAD

**Issue by ZDevelop94** [ZDevelop94/NBG_IMS2#8]
There are not enough fields on this page that are needed to match what is required to create a new order. 

- **Takeout product ID field** this will be automatically generated
- This HTML shouldn't be called order as we are creating a new product
- Fields that need adding:
description
price
category
porous allowed
porous applied
all the above product information is relevant fro product creation

**Comment by DanielAjibike** [comment]
This page is for adding and decrementing existing stock. The page you are referring to is being handled by Ben
